server:
  port: 8888
spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsjyz?unicode=true&characterSet=utf-8&TimeZone=UTC
    hikari:
      max-lifetime: 600000
#  sql:
#    init:
#      schema-locations: classpath*:sql/*.sql
#      data-locations: classpath*:sql/data/*.sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

